# https://taskfile.dev

version: '3'


vars:
  DEFAULT_BRANCH: main # Replace with your default branch if different

tasks:
  test:
    desc: run tests for the project
    cmds:
      - go generate ./...
      - go test -coverprofile=coverage.out ./...

  coverage:
    desc: generate coverage report
    deps: [test]
    cmds:
      - go tool cover -html=coverage.out

  tag:
    desc: run the tagging program on my database and tag all the things
    cmds:
      - go run cmd/main.go p query | awk -F'[(|)]' '{print $2}' | xargs -I {} go run cmd/main.go p tag --page_id {}

  lint:
    desc: run linters on the project
    cmds:
      - golangci-lint run

  deps:
    desc: install dependencies
    cmds:
      - go mod tidy
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/goreleaser/goreleaser@latest
      - go install github.com/klauern/bump/cmd/bump@latest
      - go install go.uber.org/mock/mockgen@latest

  bump:patch:
    desc: "Create a patch version bump"
    cmds:
      - bump patch

  bump:minor:
    desc: "Create a minor version bump"
    cmds:
      - bump minor

  bump:major:
    desc: "Create a major version bump"
    cmds:
      - bump major
